version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - botnet

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: telegram_publisher
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - TOKEN=${TOKEN_TELEGRAM}
    depends_on:
      - rabbitmq
    networks:
      - botnet

volumes:
  rabbitmq_data:

networks:
  botnet:
    driver: bridge
