FROM python:3.11-slim

WORKDIR /app

COPY message_replicator /app
COPY .env.messager /app/.env  # <- Adiciona o .env dentro do container

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-u", "main.py"]
