FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY main.py .
COPY .env.messager .env    # <- copia o .env específico com o nome padrão

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
